language: android

# Turning off caching to avoid caching Issues
# cache: false
# Using the new Container-Based Infrastructure
sudo: false

env:
  global:
    # Initiating clean Gradle output
    - TERM=dumb
    # Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    # General Android settings used in builds
    - ANDROID_TARGET=android-22

before_install:
    # Making sure gradlew has executable permissions
    - cd UltimateRecyclerView
    - chmod a+x gradlew

android:
  components:
    # We are using the latest revision of Android SDK Tools

    - android-23
    # The BuildTools version we are using for our project
    - build-tools-23.0.2
    
    - platform-tools
    - tools
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
     - 'android-sdk-license-.+'

script:

  #./gradlew build
  ./gradlew assembleDebug
